package guitest;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author guan97005
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form dawpl
     */
    public JFrame() {
        
        initComponents();
        addRowToJTable();
        hideColumnId();
        jScrollPane1.getColumnHeader().setVisible(false);
    }
    
    public static String sortQuery = "SELECT * FROM filmer";
    
    //Metod som ansluter till databasen
    public java.sql.Connection getConnection() {
        java.sql.Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/filmregister", "root", "");
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    //Göm kolumnen med ID
    public void hideColumnId(){
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    
    //Gör inmatningsfälten tomma
    public void emptyFields(){
        newTitle.setText("");
        newGenre.setText("");
        newDirector.setText("");
        newIMDb.setText("");
        newLength.setText("");
    }
    
    
    
    //Arraylist där filmerna lagras
    public ArrayList listFilmer() {
        ArrayList<Filmer> list = new ArrayList<Filmer>();
        Connection connection = getConnection();
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(sortQuery);
            Filmer film;
            
            while (rs.next()) {
                film = new Filmer(rs.getInt("id"), rs.getString("titel"), rs.getString("genre"), rs.getString("regissör"), rs.getString("iMDb"), rs.getString("längd"));
                list.add(film);
            }
        } catch (SQLException ex) {
            System.out.println("Gör om, gör rätt");
        }
        return list;
    }
    
    //Filmerna läggs till i JTabeln
    public void addRowToJTable() {
        ArrayList<Filmer> list = listFilmer();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object []rowData = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getTitel();
            rowData[2] = list.get(i).getGenre();
            rowData[3] = list.get(i).getRegissör();
            rowData[4] = list.get(i).getIMDb();
            rowData[5] = list.get(i).getLängd();
            model.addRow(rowData);

        }
    }
    
    //Uppdaterar JTabeln när någon förändring gjorts
    public void refresh(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        addRowToJTable();        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newTitle = new javax.swing.JTextField();
        newGenre = new javax.swing.JTextField();
        newDirector = new javax.swing.JTextField();
        newIMDb = new javax.swing.JTextField();
        newLength = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        headerTitle = new javax.swing.JLabel();
        headerGenre = new javax.swing.JLabel();
        headerDirector = new javax.swing.JLabel();
        headerIMDb = new javax.swing.JLabel();
        headerLength = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        getID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1340, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Movie Database");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(580, 20, 240, 65);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Genre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 250, 50, 26);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Title");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 150, 40, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Director");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 340, 60, 26);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("IMDb");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 430, 40, 26);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Length");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 520, 50, 26);

        newTitle.setSelectionColor(new java.awt.Color(0, 0, 0));
        newTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTitleActionPerformed(evt);
            }
        });
        jPanel1.add(newTitle);
        newTitle.setBounds(80, 200, 161, 30);

        newGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGenreActionPerformed(evt);
            }
        });
        jPanel1.add(newGenre);
        newGenre.setBounds(80, 290, 161, 30);

        newDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDirectorActionPerformed(evt);
            }
        });
        jPanel1.add(newDirector);
        newDirector.setBounds(80, 380, 161, 30);

        newIMDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newIMDbActionPerformed(evt);
            }
        });
        jPanel1.add(newIMDb);
        newIMDb.setBounds(80, 470, 161, 30);

        newLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLengthActionPerformed(evt);
            }
        });
        jPanel1.add(newLength);
        newLength.setBounds(80, 560, 161, 30);

        addButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/add1.png"))); // NOI18N
        addButton.setText("Insert");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);
        addButton.setBounds(110, 640, 103, 29);

        updateButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/rotate1.png"))); // NOI18N
        updateButton.setText("Update");
        jPanel1.add(updateButton);
        updateButton.setBounds(720, 650, 103, 29);

        removeButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/remove1.png"))); // NOI18N
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeButton);
        removeButton.setBounds(1050, 650, 103, 29);

        headerTitle.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        headerTitle.setForeground(new java.awt.Color(255, 255, 255));
        headerTitle.setText("Title");
        headerTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerTitleMouseClicked(evt);
            }
        });
        jPanel1.add(headerTitle);
        headerTitle.setBounds(420, 110, 40, 26);

        headerGenre.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        headerGenre.setForeground(new java.awt.Color(255, 255, 255));
        headerGenre.setText("Genre");
        headerGenre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerGenreMouseClicked(evt);
            }
        });
        jPanel1.add(headerGenre);
        headerGenre.setBounds(650, 110, 50, 30);

        headerDirector.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        headerDirector.setForeground(new java.awt.Color(255, 255, 255));
        headerDirector.setText("Director");
        headerDirector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerDirectorMouseClicked(evt);
            }
        });
        jPanel1.add(headerDirector);
        headerDirector.setBounds(870, 110, 60, 26);

        headerIMDb.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        headerIMDb.setForeground(new java.awt.Color(255, 255, 255));
        headerIMDb.setText("IMDb");
        headerIMDb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerIMDbMouseClicked(evt);
            }
        });
        jPanel1.add(headerIMDb);
        headerIMDb.setBounds(1050, 110, 40, 26);

        headerLength.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        headerLength.setForeground(new java.awt.Color(255, 255, 255));
        headerLength.setText("Length");
        headerLength.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerLengthMouseClicked(evt);
            }
        });
        jPanel1.add(headerLength);
        headerLength.setBounds(1170, 110, 50, 26);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Genre", "Director", "IMDb", "Length"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(0, 102, 102));
        jTable1.setRowHeight(40);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(220);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(170);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(320, 160, 970, 470);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/rsz_1registerbackground.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 1360, 690);

        getID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(getID);
        getID.setBounds(1291, 11, 22, 11);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-2, -2, 1360, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newLengthActionPerformed

    private void newIMDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newIMDbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newIMDbActionPerformed

    private void newDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDirectorActionPerformed

    private void newGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newGenreActionPerformed

    private void newTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newTitleActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        try {
            Connection connection = getConnection();
            Statement stmt = connection.createStatement();
            String sql = "INSERT INTO `filmer` (`Titel`, `Genre`, `Regissör`, `IMDb`, `Längd`) VALUES ('" + newTitle.getText() + "','" + newGenre.getText() + "','" + newDirector.getText() + "','" + newIMDb.getText()+ "','" + newLength.getText() + "')";
            stmt.executeUpdate(sql);
            refresh();
            emptyFields();
            
 
        } catch (SQLException ex) {
            System.out.println("Gör om, gör rätt");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed

        try {
            Connection connection = getConnection();
            Statement stmt = connection.createStatement();
            String sql = "DELETE FROM `filmer` WHERE `filmer`.`id` = "+getID.getText();
            stmt.executeUpdate(sql);
            refresh();
 
        } catch (SQLException ex) {
            System.out.println("Gör om, gör rätt");
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    //Bestämmer vilken filmrad man klickat på
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        getID.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void headerTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerTitleMouseClicked
        sortQuery = "SELECT * FROM filmer order BY Titel";
        refresh();
    }//GEN-LAST:event_headerTitleMouseClicked

    private void headerGenreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerGenreMouseClicked
        sortQuery = "SELECT * FROM filmer order BY Genre";
        refresh();
    }//GEN-LAST:event_headerGenreMouseClicked

    private void headerDirectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerDirectorMouseClicked
        sortQuery = "SELECT * FROM filmer order BY Regissör";
        refresh();
    }//GEN-LAST:event_headerDirectorMouseClicked

    private void headerIMDbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerIMDbMouseClicked
        sortQuery = "SELECT * FROM filmer order BY IMDb desc";
        refresh();
    }//GEN-LAST:event_headerIMDbMouseClicked

    private void headerLengthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerLengthMouseClicked
        sortQuery = "SELECT * FROM filmer order by Längd desc";
        refresh();
    }//GEN-LAST:event_headerLengthMouseClicked
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel getID;
    private javax.swing.JLabel headerDirector;
    private javax.swing.JLabel headerGenre;
    private javax.swing.JLabel headerIMDb;
    private javax.swing.JLabel headerLength;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField newDirector;
    private javax.swing.JTextField newGenre;
    private javax.swing.JTextField newIMDb;
    private javax.swing.JTextField newLength;
    private javax.swing.JTextField newTitle;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
